#!/bin/sh
export QEMU_AUDIO_DRV=none
qemu-system-arm \
	-machine realview-pbx-a9 \
	-cpu cortex-a9 \
	-s -S \
	-kernel bin/davros.elf \
	-hda /dev/zero \
	-monitor stdio \
	-nographic \
	-serial pty 

#	-machine integratorcp
